# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 腹有诗书气自华的毛毛亮
subtitle: Change myself or Keep myself
description: &nbsp;&nbsp;&nbsp;&nbsp;感觉还可以再强一点！
author: 毛毛亮
language: zh-CN
timezone:
keywords: "菜鸟Web开发者,菜鸟经济管理学院研究生,真的菜"

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://maomaoliang.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# 百度统计
baidu_analytics: 34f089c6238a8954f7a11596c82077f0

# 头像设置
avatar: http://maomaoliang.github.io/assets/blogImg/mamaoliang.jpg

# JiaThis 分享服务
#jiathis: true

# 百度分享服务
#baidushare: true

# Swiftype Search Key
# swiftype_key: hdUL6xonNozsy_ewSMxF

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
# Plugins: http://hexo.io/plugins/
# themes: http://hexo.io/themes/
theme: next

# 搜索插件
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Social links
social:
  github: https://github.com/maomaoliang
  twitter: https://twitter.com/your-user-name
  weibo: http://weibo.com/u/1800376583?from=myfollow_group&is_all=1
  # douban: http://douban.com/people/your-user-name
  zhihu: https://www.zhihu.com/people/maomaomaoliang
  # 等等

# feed setting
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  
# title, chinese available
links_title: Links
# links
links:
  Google: http://www.google.com/

# Deployment
## Docs: http://hexo.io/docs/deployment.html
## 不要用 git 协议或者 ssh 方式 clone repo，用 https 协议，并且设置公司 http 代理：
deploy:
  type: git
  #repository: git@github.com:maomaoliang/maomaoliang.github.io.git
  repository:  https://github.com/maomaoliang/maomaoliang.github.io.git
  branch: master

# 修改本地端口号
server:
  port: 4001
  compress: true
  header: true

